// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("a062f2c5-e92e-44d8-ae3f-04f2c90e190d"),
	startsWith("36868dee-b650-4148-b1e2-4c4af9af9e98"),
	endsWith("6682dcc2-aa42-4192-b52e-55c65afed920"),
	between("a5067cdb-4a2a-4677-a6f5-d7e502413f24"),
	greater("a2b31751-f965-4ab5-bc66-2a8b53409a7f"),
	greaterEqual("fddc04ef-a036-442f-955a-e6b46f190f9f"),
	equal("ed42ba87-ffc6-4a2a-bb8e-f678340d8134"),
	notEqual("702d8e0c-9c13-4339-b30d-b10312d886c0"),
	smaller("0bec766a-996c-4db7-a09e-ff4dcaad454d"),
	smallerEqual("bf4cb1b2-b843-4b2a-bdcf-9d7fc74553a3"),
	empty("1cf28013-cd2e-45e7-843a-e4ffa52dc5dc"),
	notEmpty("2536354a-7127-474d-9e4c-02f7b17df398");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
