// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the TestModule module
	public static void aCT_Block_GenerateItems(IContext context, testmodule.proxies.Block _block)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Block", _block == null ? null : _block.getMendixObject());
		Core.microflowCall("TestModule.ACT_Block_GenerateItems").withParams(params).execute(context);
	}
	public static void aCT_Block_NewItem(IContext context, testmodule.proxies.Block _block)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Block", _block == null ? null : _block.getMendixObject());
		Core.microflowCall("TestModule.ACT_Block_NewItem").withParams(params).execute(context);
	}
	public static void aCT_Block_SaveNew(IContext context, testmodule.proxies.Block _block)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Block", _block == null ? null : _block.getMendixObject());
		Core.microflowCall("TestModule.ACT_Block_SaveNew").withParams(params).execute(context);
	}
	public static void aCT_TestSet_SaveNew(IContext context, testmodule.proxies.TestSet _testSet)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestSet", _testSet == null ? null : _testSet.getMendixObject());
		Core.microflowCall("TestModule.ACT_TestSet_SaveNew").withParams(params).execute(context);
	}
}