// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativecustomscrollview.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestNativeCustomScrollView module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Block_GenerateItemsBuilder(
		testnativecustomscrollview.proxies.Block _block
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeCustomScrollView.ACT_Block_GenerateItems");
		builder = builder.withParam("Block", _block);
		return builder;
	}

	public static void aCT_Block_GenerateItems(
		IContext context,
		testnativecustomscrollview.proxies.Block _block
	)
	{
		aCT_Block_GenerateItemsBuilder(
				_block
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Block_NewItemBuilder(
		testnativecustomscrollview.proxies.Block _block
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeCustomScrollView.ACT_Block_NewItem");
		builder = builder.withParam("Block", _block);
		return builder;
	}

	public static void aCT_Block_NewItem(
		IContext context,
		testnativecustomscrollview.proxies.Block _block
	)
	{
		aCT_Block_NewItemBuilder(
				_block
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Block_SaveNewBuilder(
		testnativecustomscrollview.proxies.Block _block
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeCustomScrollView.ACT_Block_SaveNew");
		builder = builder.withParam("Block", _block);
		return builder;
	}

	public static void aCT_Block_SaveNew(
		IContext context,
		testnativecustomscrollview.proxies.Block _block
	)
	{
		aCT_Block_SaveNewBuilder(
				_block
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestSet_SaveNewBuilder(
		testnativecustomscrollview.proxies.TestSet _testSet
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeCustomScrollView.ACT_TestSet_SaveNew");
		builder = builder.withParam("TestSet", _testSet);
		return builder;
	}

	public static void aCT_TestSet_SaveNew(
		IContext context,
		testnativecustomscrollview.proxies.TestSet _testSet
	)
	{
		aCT_TestSet_SaveNewBuilder(
				_testSet
			)
			.execute(context);
	}
}
