// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativecustomscrollview.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the TestNativeCustomScrollView module
	public static void aCT_Block_GenerateItems(IContext context, testnativecustomscrollview.proxies.Block _block)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Block", _block == null ? null : _block.getMendixObject());
		Core.microflowCall("TestNativeCustomScrollView.ACT_Block_GenerateItems").withParams(params).execute(context);
	}
	public static void aCT_Block_NewItem(IContext context, testnativecustomscrollview.proxies.Block _block)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Block", _block == null ? null : _block.getMendixObject());
		Core.microflowCall("TestNativeCustomScrollView.ACT_Block_NewItem").withParams(params).execute(context);
	}
	public static void aCT_Block_SaveNew(IContext context, testnativecustomscrollview.proxies.Block _block)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Block", _block == null ? null : _block.getMendixObject());
		Core.microflowCall("TestNativeCustomScrollView.ACT_Block_SaveNew").withParams(params).execute(context);
	}
	public static void aCT_TestSet_SaveNew(IContext context, testnativecustomscrollview.proxies.TestSet _testSet)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestSet", _testSet == null ? null : _testSet.getMendixObject());
		Core.microflowCall("TestNativeCustomScrollView.ACT_TestSet_SaveNew").withParams(params).execute(context);
	}
}
