// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativecustomscrollview.proxies;

public class NativeAppContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nativeAppContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestNativeCustomScrollView.NativeAppContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ScrollToTopTrigger("ScrollToTopTrigger"),
		ScrollToID("ScrollToID"),
		AnimateScroll("AnimateScroll"),
		CloseBeforeScroll("CloseBeforeScroll"),
		NativeAppContext_TestSet("TestNativeCustomScrollView.NativeAppContext_TestSet"),
		CurrentBlock("TestNativeCustomScrollView.CurrentBlock"),
		NativeAppContext_Item_ScrollTo("TestNativeCustomScrollView.NativeAppContext_Item_ScrollTo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NativeAppContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NativeAppContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nativeAppContextMendixObject)
	{
		if (nativeAppContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!nativeAppContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.nativeAppContextMendixObject = nativeAppContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testnativecustomscrollview.proxies.NativeAppContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testnativecustomscrollview.proxies.NativeAppContext(context, mendixObject);
	}

	public static testnativecustomscrollview.proxies.NativeAppContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testnativecustomscrollview.proxies.NativeAppContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of ScrollToTopTrigger
	 */
	public final java.util.Date getScrollToTopTrigger()
	{
		return getScrollToTopTrigger(getContext());
	}

	/**
	 * @param context
	 * @return value of ScrollToTopTrigger
	 */
	public final java.util.Date getScrollToTopTrigger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ScrollToTopTrigger.toString());
	}

	/**
	 * Set value of ScrollToTopTrigger
	 * @param scrolltotoptrigger
	 */
	public final void setScrollToTopTrigger(java.util.Date scrolltotoptrigger)
	{
		setScrollToTopTrigger(getContext(), scrolltotoptrigger);
	}

	/**
	 * Set value of ScrollToTopTrigger
	 * @param context
	 * @param scrolltotoptrigger
	 */
	public final void setScrollToTopTrigger(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date scrolltotoptrigger)
	{
		getMendixObject().setValue(context, MemberNames.ScrollToTopTrigger.toString(), scrolltotoptrigger);
	}

	/**
	 * @return value of ScrollToID
	 */
	public final java.lang.String getScrollToID()
	{
		return getScrollToID(getContext());
	}

	/**
	 * @param context
	 * @return value of ScrollToID
	 */
	public final java.lang.String getScrollToID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ScrollToID.toString());
	}

	/**
	 * Set value of ScrollToID
	 * @param scrolltoid
	 */
	public final void setScrollToID(java.lang.String scrolltoid)
	{
		setScrollToID(getContext(), scrolltoid);
	}

	/**
	 * Set value of ScrollToID
	 * @param context
	 * @param scrolltoid
	 */
	public final void setScrollToID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scrolltoid)
	{
		getMendixObject().setValue(context, MemberNames.ScrollToID.toString(), scrolltoid);
	}

	/**
	 * @return value of AnimateScroll
	 */
	public final java.lang.Boolean getAnimateScroll()
	{
		return getAnimateScroll(getContext());
	}

	/**
	 * @param context
	 * @return value of AnimateScroll
	 */
	public final java.lang.Boolean getAnimateScroll(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AnimateScroll.toString());
	}

	/**
	 * Set value of AnimateScroll
	 * @param animatescroll
	 */
	public final void setAnimateScroll(java.lang.Boolean animatescroll)
	{
		setAnimateScroll(getContext(), animatescroll);
	}

	/**
	 * Set value of AnimateScroll
	 * @param context
	 * @param animatescroll
	 */
	public final void setAnimateScroll(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean animatescroll)
	{
		getMendixObject().setValue(context, MemberNames.AnimateScroll.toString(), animatescroll);
	}

	/**
	 * @return value of CloseBeforeScroll
	 */
	public final java.lang.Boolean getCloseBeforeScroll()
	{
		return getCloseBeforeScroll(getContext());
	}

	/**
	 * @param context
	 * @return value of CloseBeforeScroll
	 */
	public final java.lang.Boolean getCloseBeforeScroll(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CloseBeforeScroll.toString());
	}

	/**
	 * Set value of CloseBeforeScroll
	 * @param closebeforescroll
	 */
	public final void setCloseBeforeScroll(java.lang.Boolean closebeforescroll)
	{
		setCloseBeforeScroll(getContext(), closebeforescroll);
	}

	/**
	 * Set value of CloseBeforeScroll
	 * @param context
	 * @param closebeforescroll
	 */
	public final void setCloseBeforeScroll(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean closebeforescroll)
	{
		getMendixObject().setValue(context, MemberNames.CloseBeforeScroll.toString(), closebeforescroll);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NativeAppContext_TestSet
	 */
	public final testnativecustomscrollview.proxies.TestSet getNativeAppContext_TestSet() throws com.mendix.core.CoreException
	{
		return getNativeAppContext_TestSet(getContext());
	}

	/**
	 * @param context
	 * @return value of NativeAppContext_TestSet
	 * @throws com.mendix.core.CoreException
	 */
	public final testnativecustomscrollview.proxies.TestSet getNativeAppContext_TestSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testnativecustomscrollview.proxies.TestSet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NativeAppContext_TestSet.toString());
		if (identifier != null) {
			result = testnativecustomscrollview.proxies.TestSet.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NativeAppContext_TestSet
	 * @param nativeappcontext_testset
	 */
	public final void setNativeAppContext_TestSet(testnativecustomscrollview.proxies.TestSet nativeappcontext_testset)
	{
		setNativeAppContext_TestSet(getContext(), nativeappcontext_testset);
	}

	/**
	 * Set value of NativeAppContext_TestSet
	 * @param context
	 * @param nativeappcontext_testset
	 */
	public final void setNativeAppContext_TestSet(com.mendix.systemwideinterfaces.core.IContext context, testnativecustomscrollview.proxies.TestSet nativeappcontext_testset)
	{
		if (nativeappcontext_testset == null) {
			getMendixObject().setValue(context, MemberNames.NativeAppContext_TestSet.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NativeAppContext_TestSet.toString(), nativeappcontext_testset.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CurrentBlock
	 */
	public final testnativecustomscrollview.proxies.Block getCurrentBlock() throws com.mendix.core.CoreException
	{
		return getCurrentBlock(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentBlock
	 * @throws com.mendix.core.CoreException
	 */
	public final testnativecustomscrollview.proxies.Block getCurrentBlock(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testnativecustomscrollview.proxies.Block result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CurrentBlock.toString());
		if (identifier != null) {
			result = testnativecustomscrollview.proxies.Block.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CurrentBlock
	 * @param currentblock
	 */
	public final void setCurrentBlock(testnativecustomscrollview.proxies.Block currentblock)
	{
		setCurrentBlock(getContext(), currentblock);
	}

	/**
	 * Set value of CurrentBlock
	 * @param context
	 * @param currentblock
	 */
	public final void setCurrentBlock(com.mendix.systemwideinterfaces.core.IContext context, testnativecustomscrollview.proxies.Block currentblock)
	{
		if (currentblock == null) {
			getMendixObject().setValue(context, MemberNames.CurrentBlock.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CurrentBlock.toString(), currentblock.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NativeAppContext_Item_ScrollTo
	 */
	public final testnativecustomscrollview.proxies.Item getNativeAppContext_Item_ScrollTo() throws com.mendix.core.CoreException
	{
		return getNativeAppContext_Item_ScrollTo(getContext());
	}

	/**
	 * @param context
	 * @return value of NativeAppContext_Item_ScrollTo
	 * @throws com.mendix.core.CoreException
	 */
	public final testnativecustomscrollview.proxies.Item getNativeAppContext_Item_ScrollTo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testnativecustomscrollview.proxies.Item result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NativeAppContext_Item_ScrollTo.toString());
		if (identifier != null) {
			result = testnativecustomscrollview.proxies.Item.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NativeAppContext_Item_ScrollTo
	 * @param nativeappcontext_item_scrollto
	 */
	public final void setNativeAppContext_Item_ScrollTo(testnativecustomscrollview.proxies.Item nativeappcontext_item_scrollto)
	{
		setNativeAppContext_Item_ScrollTo(getContext(), nativeappcontext_item_scrollto);
	}

	/**
	 * Set value of NativeAppContext_Item_ScrollTo
	 * @param context
	 * @param nativeappcontext_item_scrollto
	 */
	public final void setNativeAppContext_Item_ScrollTo(com.mendix.systemwideinterfaces.core.IContext context, testnativecustomscrollview.proxies.Item nativeappcontext_item_scrollto)
	{
		if (nativeappcontext_item_scrollto == null) {
			getMendixObject().setValue(context, MemberNames.NativeAppContext_Item_ScrollTo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NativeAppContext_Item_ScrollTo.toString(), nativeappcontext_item_scrollto.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nativeAppContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testnativecustomscrollview.proxies.NativeAppContext that = (testnativecustomscrollview.proxies.NativeAppContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
