// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativecustomscrollview.proxies;

public enum SectionIDs
{
	Section1(new java.lang.String[][] { new java.lang.String[] { "en_US", "Section 1" } }),
	Section2(new java.lang.String[][] { new java.lang.String[] { "en_US", "Section 2" } }),
	Section3(new java.lang.String[][] { new java.lang.String[] { "en_US", "Section 3" } }),
	Section4(new java.lang.String[][] { new java.lang.String[] { "en_US", "Section 4" } }),
	Section5(new java.lang.String[][] { new java.lang.String[] { "en_US", "Section 5" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private SectionIDs(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
