// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("cce8d9ea-8613-47fe-90e0-7b94d2b3f010"),
	denied("4afd3fc9-df87-48a6-82d7-b8606467e04a"),
	limited("c57c7445-c67e-4ffb-ae4a-cbedbd40017c"),
	granted("89ffca8b-59ad-40ec-808b-1114bab3bcd8"),
	blocked("234856f0-9823-4bd7-8423-09070938446e");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
