// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("89382278-1fe2-43f4-965d-d62f65925dc9"),
	denied("22e2c588-924a-4891-911d-fe4c62f9a5de"),
	limited("9e73fad1-9c40-4408-9e95-cf76d0baaa8f"),
	granted("d646a9f6-aa5a-42f7-b826-d3cae5cde964"),
	blocked("3f930e39-e80f-4db0-840c-58922b90388d");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
