// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("eea6654d-1ada-4b7e-8f4e-ef2467f12568"),
	low("25c3af6d-443e-46cc-a380-d24efe19dce0"),
	medium("9950865f-47a6-44a0-a0b6-8812caec1fae"),
	high("24ad8ccd-a479-4aa7-9382-379061391013"),
	custom("68b5066f-b110-48bc-a82d-030a6a099bce");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
