// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("3a6cf225-b061-49ed-b6f1-aae8c72199b4"),
	low("22bbfdc2-d398-4a4b-bf84-f804da6eead0"),
	medium("a4e1a5f9-a093-42fb-88e5-24904071b1d9"),
	high("85c44b17-c42e-4b67-bcb6-1cfe96c61706"),
	custom("e7b5df4c-758b-4c66-812b-c04093687775");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
