// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarStyle
{
	DefaultStyle("f36108e8-da80-4b48-9cdf-b08165c8d876"),
	LightContentStyle("d5fcd46c-4d44-447d-a990-080e11a44949"),
	DarkContentStyle("35761401-ea71-4082-964a-240fe0e6fbb7");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
